name: deepchem
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - openmm
  - mdtraj
  - pdbfixer
  - pip
  - hhsuite
  - pip:
    - numpy
    - rdkit
    - pre-commit
    - biopython
    - dgllife
    - lightgbm==3.*
    - matminer
    - mordred
    - networkx
    - pillow
    - pubchempy
    - pyGPGO
    - pymatgen
    - simdna
    - transformers==4.10.*
    - xgboost
    - gensim  # used by mol2vec 
    - tensorboard
    - vina
    - -f https://download.pytorch.org/whl/cpu/torch_stable.html
    - -f https://data.pyg.org/whl/torch-1.12.0+cpu.html
    - -f https://data.dgl.ai/wheels/repo.html
    - dgl
    - torch==1.12.0+cpu
    - torch-scatter
    - torch-sparse
    - torch-geometric
    - pytorch-lightning==1.6.5
    - deepchem
    - tensorflow
    - tensorflow_probability
    - tensorflow_addons